## CFPS面板数据整合
---

In [2]:
import os
import re
import pandas as pd

In [3]:
# 参数设置
DATA_FILE_PATH = r'E:\datahouse\rawdata\microdata\final2'

In [10]:
# 导入2012年个体数据
raw_individual_2012_data = pd.read_stata(os.path.join(DATA_FILE_PATH, '2012conf.dta'), convert_categoricals = False)
raw_individual_2012_data.iloc[0:10,]

,pid,fid12,tb1b_a_p,tb1y_a_p,alive_a_p,pid_f,tb1b_a_f,tb1y_a_f,alive_a_f,pid_m,...,alive_a_c8,pid_c9,tb1b_a_c9,tb1y_a_c9,alive_a_c9,pid_c10,tb1b_a_c10,tb1y_a_c10,alive_a_c10,familysize
0,100453401,100453,0,2012,1,100453431,31.0,1981.0,1.0,430111103,...,-8,-8,-8,-8,-8,-8,-8,-8,-8,3
1,100453401,430111,-8,2012,1,-8,-8.0,-8.0,-8.0,430111103,...,-8,-8,-8,-8,-8,-8,-8,-8,-8,2
2,100453431,100453,31,1981,1,-8,-8.0,-8.0,-8.0,-8,...,-8,-8,-8,-8,-8,-8,-8,-8,-8,3
3,105179431,105179,48,1964,1,-8,-8.0,-8.0,-8.0,-8,...,-8,-8,-8,-8,-8,-8,-8,-8,-8,4
4,105179432,105179,47,1965,1,-8,-8.0,-8.0,-8.0,-8,...,-8,-8,-8,-8,-8,-8,-8,-8,-8,4
5,105179433,105179,23,1989,1,105179431,48.0,1964.0,1.0,105179432,...,-8,-8,-8,-8,-8,-8,-8,-8,-8,4
6,108640431,108640,0,2012,1,-8,-8.0,-8.0,-8.0,-8,...,-8,-8,-8,-8,-8,-8,-8,-8,-8,2
7,110002101,110002,47,1965,1,-8,-8.0,-1.0,0.0,-8,...,-8,-8,-8,-8,-8,-8,-8,-8,-8,3
8,110002102,110002,43,1969,1,-8,-8.0,-1.0,0.0,-8,...,-8,-8,-8,-8,-8,-8,-8,-8,-8,3
9,110002103,110002,18,-1,1,110002101,47.0,1965.0,1.0,110002102,...,-8,-8,-8,-8,-8,-8,-8,-8,-8,3

In [44]:
# 计算年龄
def to_age(birth_date,report_age,invest_year):
    if birth_date > 0:
        age = invest_year - birth_date
    else:
        age = -999
    if report_age is not None:
        if int(report_age) != int(age):
            if report_age >= 0:
                age = report_age
    
    return age

In [ ]:
raw_individual_2012_grouped_data = raw_individual_2012_data.groupby('fid12')
variables = list(raw_individual_2012_data.columns)
family_memeber_keywords = ['f','m','s']
family_memeber_keywords.extend([''.join(['c',str(i)]) for i in range(1,11)])

# 用来判别是否已经计入数据中
fid_set = set()
filtered_data_list = []
for fid, grouped_data in raw_individual_2012_grouped_data:
    grouped_data.index = range(grouped_data.shape[0])
    
    for ind in grouped_data.index:
        # 处理年龄，活着的才计入，无信息的年龄设定-999
        if grouped_data.loc[ind,'alive_a_p']==1:
            age = to_age(grouped_data.loc[ind,'tb1y_a_p'],grouped_data.loc[ind,'tb1b_a_p'],2012)
            
            if age < 0:
                print(grouped_data.loc[ind,'pid'],grouped_data.loc[ind,'tb1b_a_p'],grouped_data.loc[ind,'tb1y_a_p'],age)
            fid_set.add(grouped_data.loc[ind,'pid'])
            filtered_data_list.append([grouped_data.loc[ind,'pid'],grouped_data.loc[ind,'fid12'],age,grouped_data.loc[ind,'familysize']])

        for key_word in family_memeber_keywords:
            if grouped_data.loc[ind,''.join(['alive_a_',key_word])] == 1:
                age = to_age(grouped_data.loc[ind,''.join(['tb1y_a_',key_word])],grouped_data.loc[ind,''.join(['tb1b_a_',key_word])],2012)

In [42]:
list(raw_individual_2012_data.columns)

['pid',
 'fid12',
 'tb1b_a_p',
 'tb1y_a_p',
 'alive_a_p',
 'pid_f',
 'tb1b_a_f',
 'tb1y_a_f',
 'alive_a_f',
 'pid_m',
 'tb1b_a_m',
 'tb1y_a_m',
 'alive_a_m',
 'pid_s',
 'tb1b_a_s',
 'tb1y_a_s',
 'alive_a_s',
 'pid_c1',
 'tb1b_a_c1',
 'tb1y_a_c1',
 'alive_a_c1',
 'pid_c2',
 'tb1b_a_c2',
 'tb1y_a_c2',
 'alive_a_c2',
 'pid_c3',
 'tb1b_a_c3',
 'tb1y_a_c3',
 'alive_a_c3',
 'pid_c4',
 'tb1b_a_c4',
 'tb1y_a_c4',
 'alive_a_c4',
 'pid_c5',
 'tb1b_a_c5',
 'tb1y_a_c5',
 'alive_a_c5',
 'pid_c6',
 'tb1b_a_c6',
 'tb1y_a_c6',
 'alive_a_c6',
 'pid_c7',
 'tb1b_a_c7',
 'tb1y_a_c7',
 'alive_a_c7',
 'pid_c8',
 'tb1b_a_c8',
 'tb1y_a_c8',
 'alive_a_c8',
 'pid_c9',
 'tb1b_a_c9',
 'tb1y_a_c9',
 'alive_a_c9',
 'pid_c10',
 'tb1b_a_c10',
 'tb1y_a_c10',
 'alive_a_c10',
 'familysize']